version: "3.9"
services:
  vsftpd:
    restart: unless-stopped
    build:
      context: docker-vsftpd
    volumes:
      - type: bind
        source: "C:\\Users\\tim\\Desktop\\scans"
        target: /home/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      PASV_ADDRESS: "127.0.0.1"
      PASV_MIN_PORT: "21100"
      PASV_MAX_PORT: "21110"
